import type { ReptileStory } from "@/lib/reptile-news";

// Hand-checked publisher stories. Dates are publication dates, not discovery dates.
// Keep the original publisher URL and write fresh, short summaries here.
export const curatedReptileNews: ReptileStory[] = [
  {
    title: "Machine learning identifies the Burmese pythons managers should target",
    url: "https://phys.org/news/2026-10-python-index-large-females-key.html",
    publishedAt: "2026-10-01",
    publisher: "Phys.org",
    summary: "University of Florida researchers created a weighted removal index showing that targeting large reproductive females—especially during high-value winter periods—could make invasive-python control in South Florida more effective.",
  },
  {
    title: "X-ray scans dethrone a fossil long called the world's oldest reptile",
    url: "https://phys.org/news/2026-09-fossil-world-oldest-reptile-dethroned.html",
    publishedAt: "2026-09-30",
    publisher: "Phys.org",
    summary: "New scans revealed internal gills, a primitive skull, and thousands of tiny teeth in Westlothiana, showing that the 345-million-year-old animal was an aquatic or amphibious stem tetrapod rather than an early reptile.",
  },
  {
    title: "Afro-Asian sand snake documented in Kutch after 150 years",
    url: "https://indianexpress.com/article/cities/ahmedabad/kutch-afro-asian-sand-snake-sighting-gujarat-wildlife-10899757/",
    publishedAt: "2026-09-30",
    publisher: "The Indian Express",
    summary: "A forest officer photographed a Psammophis schokari in Gujarat's Kutch district, providing the first confirmed local record since 1872.",
  },
  {
    title: "Georgia researchers seek the missing picture of male sea turtles",
    url: "https://www.gpb.org/news/2026/09/29/georgia-scientists-snip-fins-figure-out-if-sea-turtle-males-are-in-trouble",
    publishedAt: "2026-09-29",
    publisher: "Georgia Public Broadcasting",
    summary: "Scientists are using DNA from eggs and deceased hatchlings to estimate male loggerhead breeding as warming nesting beaches raise concerns about sex ratios.",
  },
  {
    title: "First World Congress on Snakes opens in Sri Lanka",
    url: "https://news.mongabay.com/2026/09/global-experts-gather-in-sri-lanka-for-historic-first-world-congress-on-snakes/",
    publishedAt: "2026-09-30",
    publisher: "Mongabay",
    summary: "Researchers and conservationists from 25 countries are gathering to discuss snake biology, conservation, snakebite, and coexistence.",
  },
  {
    title: "Canada's wildlife import checks leave gaps for reptile trafficking",
    url: "https://news.mongabay.com/2026/09/illegal-wildlife-continues-to-slip-through-canadas-borders-experts-explain-how/",
    publishedAt: "2026-09-30",
    publisher: "Mongabay",
    summary: "An investigation examines how animals taken illegally abroad can enter Canada's pet trade when their origin is difficult to verify.",
  },
  {
    title: "Four endangered Asian brown giant tortoises hatch at Cincinnati Zoo",
    url: "https://cincinnatizoo.org/four-tiny-tortoises-a-huge-conservation-win/",
    publishedAt: "2026-09-29",
    publisher: "Cincinnati Zoo",
    summary: "Four hatchlings joined a coordinated breeding program aimed at maintaining genetic diversity in a species threatened by habitat loss and collection.",
  },
  {
    title: "Cambodia protects a genetic refuge for Siamese crocodiles",
    url: "https://www.theguardian.com/environment/2026/sep/29/cambodia-chorng-indigenous-communities-siamese-crocodile-endangered-conservation-aoe",
    publishedAt: "2026-09-29",
    publisher: "The Guardian",
    summary: "A protected Cardamom Mountains wetland safeguards wild Siamese crocodiles as Indigenous wardens and conservation partners monitor nests and restore the species.",
  },
  {
    title: "Forty-nine musk turtles return to a restored Pennsylvania lake",
    url: "https://www.wfmz.com/news/area/berks/reading-area/turtles-return-home-to-crystal-lake-after-restoration-project/article_ecc4068f-a07c-48b3-a0b4-0e0c358ead62.html",
    publishedAt: "2026-09-28",
    publisher: "WFMZ",
    summary: "After rehabilitation during the Crystal Lake cleanup, 49 musk turtles were released back to their home habitat on September 27.",
  },
  {
    title: "A leatherback turtle returns to Malaysia's nesting beaches",
    url: "https://www.thestar.com.my/news/environment/2026/09/28/ecowatch-a-leatherback-returns---but-is-it-a-species-comeback",
    publishedAt: "2026-09-28",
    publisher: "The Star",
    summary: "Malaysia recorded its first leatherback nesting since 2017. Conservationists are monitoring the eggs, but one nest does not yet signal a population recovery.",
  },
  {
    title: "Review questions the success of reptile and amphibian relocations",
    url: "https://pubmed.ncbi.nlm.nih.gov/42801322/",
    publishedAt: "2026-09-27",
    publisher: "Conservation Biology",
    summary: "A review of 313 translocation projects finds that lasting success is uncommon, underscoring the need to address threats and monitor animals after release.",
  },
  {
    title: "Investigation traces alleged trafficking of Amazonian turtles and lizards",
    url: "https://sumauma.com/en/tartarugas-e-bichos-preguica-para-exportacao-a-ascensao-e-queda-das-irmas-ferreyra/",
    publishedAt: "2026-09-27",
    publisher: "SUMAÚMA",
    summary: "A joint investigation examines allegations that wild animals from Peru were exported with paperwork describing them as legally sourced. The accused deny wrongdoing.",
  },
  {
    title: "Biologists move threatened olive ridley eggs to safety in California",
    url: "https://www.latimes.com/science/story/2026-09-25/biologists-move-unprecedented-orange-county-sea-turtle-eggs-to-protect-them-from-hurricane-driven-waves",
    publishedAt: "2026-09-25",
    publisher: "Los Angeles Times",
    summary: "Biologists relocated 204 eggs from California's first known olive ridley nests to protect them from hurricane-driven surf, with hatchlings planned for release.",
  },
  {
    title: "Conservation groups call for a permanent end to Vantara wildlife imports",
    url: "https://news.mongabay.com/2026/09/ngos-call-on-vantara-to-end-all-wild-animal-imports-permanently/",
    publishedAt: "2026-09-25",
    publisher: "Mongabay",
    summary: "Twenty-seven organizations seek a permanent commitment after a one-year import pause, citing concerns over the origins of animals including Galápagos iguanas.",
  },
  {
    title: "Abandoning exotic pets raises ecological concerns",
    url: "https://india.mongabay.com/2026/09/hard-to-resist-harder-to-keep/",
    publishedAt: "2026-09-25",
    publisher: "Mongabay India",
    summary: "A look at why exotic pets, including reptiles, are surrendered or released as their care becomes more demanding, and the need for better rescue options in India.",
  },
  {
    title: "Olive ridley sea turtle nests on a Southern California beach",
    url: "https://reptilesmagazine.com/olive-ridley-sea-turtle-lays-eggs-on-southern-california-beach/",
    publishedAt: "2026-09-23",
    publisher: "REPTILES Magazine",
    summary: "An olive ridley was observed nesting on a Southern California beach. Local and federal partners are protecting the site while monitoring the eggs.",
  },
  {
    title: "Shorter toes linked to hurricane survival in Silver Key anoles",
    url: "https://reptilesmagazine.com/silver-key-anoles-with-shorter-toe-lengths-survived-hurricanes-better-than-long-toed-counterparts/",
    publishedAt: "2026-09-22",
    publisher: "REPTILES Magazine",
    summary: "Researchers studying island anoles after two hurricanes found that animals with shorter hind toes were more likely to survive, a window into rapid natural selection.",
  },
];
