import Link from "next/link";
import { notFound } from "next/navigation";
import { SUPABASE_AUTH_KEY,SUPABASE_AUTH_URL } from "@/lib/supabase-auth";

export const dynamic="force-dynamic";
type Plant={slug:string;name:string;scientific_name:string;plant_group:string;description:string|null;tags:string[]|null;status:string};

export default async function PlantRecordPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;const clean=decodeURIComponent(slug).trim();if(!clean)notFound();
  const headers={apikey:SUPABASE_AUTH_KEY,Authorization:`Bearer ${SUPABASE_AUTH_KEY}`};
  const r=await fetch(`${SUPABASE_AUTH_URL}/rest/v1/plant_collections?slug=eq.${encodeURIComponent(clean)}&status=neq.PLANNED&select=slug,name,scientific_name,plant_group,description,tags,status&limit=1`,{headers,cache:"no-store"});
  if(!r.ok)notFound();const rows:Plant[]=await r.json();const plant=rows[0];if(!plant)notFound();
  return <main className="mx-auto max-w-6xl px-5 py-10 sm:px-6"><Link href="/plants" className="text-xs font-bold text-emerald-200/70">← Plant Database</Link><section className="panel mt-5 rounded-[32px] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="section-kicker">{plant.plant_group}</div><h1 className="mt-3 text-4xl font-semibold tracking-[-.035em] sm:text-5xl">{plant.name}</h1><div className="mt-2 text-base italic text-white/38">{plant.scientific_name}</div></div><span className="rounded-full border border-emerald-300/15 bg-emerald-300/[.05] px-3 py-1.5 text-[10px] font-black uppercase tracking-[.12em] text-emerald-200/70">{plant.status}</span></div>{plant.description&&<p className="mt-7 max-w-3xl text-sm leading-7 text-white/55">{plant.description}</p>}{plant.tags?.length?<div className="mt-6 flex flex-wrap gap-2">{plant.tags.map(t=><span key={t} className="rounded-full border border-white/[.07] px-3 py-1.5 text-[10px] text-white/35">{t}</span>)}</div>:null}</section><section className="mt-6 grid gap-4 md:grid-cols-3"><div className="panel rounded-3xl p-5"><div className="section-kicker">Reference status</div><p className="mt-3 text-sm leading-6 text-white/40">This page only exposes the structured information currently stored for this collection. Cultivation details should be added as verified fields rather than guessed into the record.</p></div><Link href="/marketplace?category=PLANT" className="panel rounded-3xl p-5 transition hover:bg-emerald-300/[.025]"><div className="section-kicker">Marketplace</div><div className="mt-3 font-semibold">Browse plant listings →</div><p className="mt-2 text-xs leading-5 text-white/32">Live seller inventory stays separate from reference content.</p></Link><Link href="/community" className="panel rounded-3xl p-5 transition hover:bg-white/[.025]"><div className="section-kicker">Community</div><div className="mt-3 font-semibold">Cultivation discussion →</div><p className="mt-2 text-xs leading-5 text-white/32">Keeper experience can inform future review without becoming a database fact automatically.</p></Link></section></main>;
}
