import { NextRequest,NextResponse } from "next/server";
import { fetchOwnProfile,getServerIdentity,SUPABASE_AUTH_KEY,SUPABASE_AUTH_URL } from "@/lib/supabase-auth";

async function adminIdentity(){const identity=await getServerIdentity();if(!identity)return null;const profile=await fetchOwnProfile(identity.token,identity.user.id) as {role?:string}|null;if(!profile||!["admin","owner"].includes(profile.role??""))return null;return identity;}

export async function GET(){const identity=await adminIdentity();if(!identity)return NextResponse.json({error:"Not found"},{status:404});const select="id,post_id,reporter_id,reason,status,created_at,reviewed_at,post:community_posts!community_post_reports_post_id_fkey(id,author_id,type,body,created_at,deleted_at),reporter:profiles!community_post_reports_reporter_id_fkey(username,display_name)";const r=await fetch(`${SUPABASE_AUTH_URL}/rest/v1/community_post_reports?select=${encodeURIComponent(select)}&order=created_at.desc&limit=100`,{headers:{apikey:SUPABASE_AUTH_KEY,Authorization:`Bearer ${identity.token}`},cache:"no-store"});if(!r.ok)return NextResponse.json({error:"Moderation queue unavailable"},{status:502});return NextResponse.json({rows:await r.json()});}

export async function PATCH(request:NextRequest){const identity=await adminIdentity();if(!identity)return NextResponse.json({error:"Not found"},{status:404});const b=await request.json().catch(()=>({}));const reportId=String(b.reportId??"");const status=String(b.status??"");const allowed=new Set(["REVIEWED","DISMISSED","ACTIONED"]);if(!reportId||!allowed.has(status))return NextResponse.json({error:"Invalid review action"},{status:400});const find=await fetch(`${SUPABASE_AUTH_URL}/rest/v1/community_post_reports?id=eq.${encodeURIComponent(reportId)}&select=id,post_id`,{headers:{apikey:SUPABASE_AUTH_KEY,Authorization:`Bearer ${identity.token}`},cache:"no-store"});const rows=find.ok?await find.json():[];if(!rows.length)return NextResponse.json({error:"Report not found"},{status:404});if(Boolean(b.hidePost)){const hide=await fetch(`${SUPABASE_AUTH_URL}/rest/v1/community_posts?id=eq.${rows[0].post_id}`,{method:"PATCH",headers:{apikey:SUPABASE_AUTH_KEY,Authorization:`Bearer ${identity.token}`,"Content-Type":"application/json"},body:JSON.stringify({deleted_at:new Date().toISOString(),updated_at:new Date().toISOString()}),cache:"no-store"});if(!hide.ok)return NextResponse.json({error:"Could not hide reported post"},{status:400});}
const update=await fetch(`${SUPABASE_AUTH_URL}/rest/v1/community_post_reports?id=eq.${encodeURIComponent(reportId)}`,{method:"PATCH",headers:{apikey:SUPABASE_AUTH_KEY,Authorization:`Bearer ${identity.token}`,"Content-Type":"application/json"},body:JSON.stringify({status,reviewed_at:new Date().toISOString()}),cache:"no-store"});if(!update.ok)return NextResponse.json({error:"Could not update report"},{status:400});return NextResponse.json({ok:true});}
