import Link from "next/link";
import { notFound } from "next/navigation";
import { SUPABASE_AUTH_KEY,SUPABASE_AUTH_URL } from "@/lib/supabase-auth";

export const dynamic="force-dynamic";
type EventRow={id:string;slug:string;title:string;organizer:string|null;event_type:string;description:string|null;starts_at:string;ends_at:string|null;time_zone:string|null;venue_name:string|null;address:string|null;city:string;state_region:string|null;country:string;website_url:string|null;source_url:string;image_url:string|null;featured:boolean;status:string};
const labels:Record<string,string>={REPTILE_EXPO:"Reptile expo",BREEDER_EVENT:"Breeder event",EDUCATION:"Education / talk",PLANT_EVENT:"Plant event",COMMUNITY_MEETUP:"Community meetup",OTHER:"Other"};
function when(start:string,end:string|null,timeZone:string|null){const a=new Date(start),b=end?new Date(end):null;const options:Intl.DateTimeFormatOptions={weekday:"short",month:"long",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",...(timeZone?{timeZone}:{}),timeZoneName:"short"};const startText=a.toLocaleString(undefined,options);if(!b)return startText;const endText=b.toLocaleString(undefined,options);return `${startText} – ${endText}`}

export default async function EventPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const clean=decodeURIComponent(slug).trim();if(!clean)notFound();
 const response=await fetch(`${SUPABASE_AUTH_URL}/rest/v1/events?slug=eq.${encodeURIComponent(clean)}&status=eq.PUBLISHED&select=id,slug,title,organizer,event_type,description,starts_at,ends_at,time_zone,venue_name,address,city,state_region,country,website_url,source_url,image_url,featured,status&limit=1`,{headers:{apikey:SUPABASE_AUTH_KEY,Authorization:`Bearer ${SUPABASE_AUTH_KEY}`},cache:"no-store"});
 if(!response.ok)notFound();const rows:EventRow[]=await response.json();const event=rows[0];if(!event)notFound();
 const place=[event.venue_name,event.address,event.city,event.state_region,event.country].filter(Boolean).join(" · ");
 return <main className="mx-auto max-w-6xl px-5 py-10 pb-20 sm:px-6">
  <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/events" className="text-xs font-bold text-emerald-200/70">← Shows & Events</Link>{event.featured?<span className="rounded-full border border-amber-200/15 bg-amber-200/[.03] px-3 py-1.5 text-[9px] font-black uppercase tracking-[.12em] text-amber-100/60">Featured event</span>:null}</div>
  <section className="panel mt-5 overflow-hidden rounded-[30px]">{event.image_url?<img src={event.image_url} alt="" className="max-h-[420px] w-full border-b border-white/[.055] object-cover"/>:null}<div className="p-6 sm:p-8"><div className="section-kicker">{labels[event.event_type]??event.event_type}</div><h1 className="mt-3 max-w-4xl text-4xl font-semibold tracking-[-.04em] sm:text-5xl">{event.title}</h1>{event.organizer?<div className="mt-3 text-sm text-white/38">Organized by {event.organizer}</div>:null}{event.description?<p className="mt-6 max-w-3xl whitespace-pre-wrap text-sm leading-7 text-white/52">{event.description}</p>:null}</div></section>
  <section className="mt-5 grid gap-4 lg:grid-cols-[1fr_.8fr]">
   <div className="panel rounded-[26px] p-6"><div className="section-kicker">Event details</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="panel-soft rounded-2xl p-4"><div className="text-[9px] font-black uppercase tracking-[.12em] text-white/24">When</div><div className="mt-2 text-sm leading-6 text-white/62">{when(event.starts_at,event.ends_at,event.time_zone)}</div>{event.time_zone?<div className="mt-2 text-[10px] text-white/25">{event.time_zone}</div>:null}</div><div className="panel-soft rounded-2xl p-4"><div className="text-[9px] font-black uppercase tracking-[.12em] text-white/24">Where</div><div className="mt-2 text-sm leading-6 text-white/62">{place}</div></div></div></div>
   <aside className="space-y-4"><div className="panel rounded-[26px] p-6"><div className="section-kicker">Verify details</div><p className="mt-3 text-xs leading-6 text-white/38">Dates, hours, venue details and admission can change. Use the original event source before making travel plans.</p><div className="mt-5 flex flex-wrap gap-3"><Link href={event.source_url} target="_blank" rel="noreferrer" className="primary-action">Official source ↗</Link>{event.website_url&&event.website_url!==event.source_url?<Link href={event.website_url} target="_blank" rel="noreferrer" className="secondary-action">Event website ↗</Link>:null}</div></div><Link href={`/community?q=${encodeURIComponent(event.title)}`} className="panel block rounded-[26px] p-6 transition hover:bg-white/[.025]"><div className="section-kicker">Community</div><div className="mt-2 font-semibold text-white/68">Discuss this event →</div><p className="mt-2 text-xs leading-5 text-white/32">See whether keepers are talking about the show without treating Community posts as official event details.</p></Link></aside>
  </section>
 </main>;
}
