"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";

type Row={id:string;title:string;organizer:string|null;event_type:string;description:string|null;starts_at:string;ends_at:string|null;venue_name:string|null;address:string|null;city:string;state_region:string|null;country:string;website_url:string|null;source_url:string;note:string|null;status:"PENDING"|"APPROVED"|"DECLINED";created_at:string;reviewed_at:string|null;time_zone:string|null};
const labels:Record<string,string>={REPTILE_EXPO:"Reptile expo",BREEDER_EVENT:"Breeder event",EDUCATION:"Education",PLANT_EVENT:"Plant event",COMMUNITY_MEETUP:"Community meetup",OTHER:"Other"};

export function AdminEventReview(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState("");
 useEffect(()=>{let active=true;void(async()=>{try{const response=await fetch("/api/admin/events",{cache:"no-store"});const data=await response.json().catch(()=>null) as {rows?:Row[];error?:string}|null;if(!active)return;if(!response.ok)throw new Error(data?.error||"Could not load event submissions.");setRows(data?.rows??[])}catch(error){if(active)setMessage(error instanceof Error?error.message:"Could not load event submissions.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 const pending=useMemo(()=>rows.filter(row=>row.status==="PENDING"),[rows]);const reviewed=useMemo(()=>rows.filter(row=>row.status!=="PENDING"),[rows]);
 async function review(id:string,action:"APPROVE"|"DECLINE"){
  if(action==="APPROVE"&&!window.confirm("Approve and publish this event to the public calendar?"))return;
  if(action==="DECLINE"&&!window.confirm("Decline this event suggestion?"))return;
  setBusy(id);setMessage(action==="APPROVE"?"Publishing event…":"Declining suggestion…");
  try{const response=await fetch("/api/admin/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action})});const data=await response.json().catch(()=>null) as {error?:string}|null;if(!response.ok)throw new Error(data?.error||"Could not review event submission.");setRows(current=>current.map(row=>row.id===id?{...row,status:action==="APPROVE"?"APPROVED":"DECLINED",reviewed_at:new Date().toISOString()}:row));setMessage(action==="APPROVE"?"Event approved and published.":"Suggestion declined.")}catch(error){setMessage(error instanceof Error?error.message:"Could not review event submission.")}finally{setBusy(null)}
 }
 if(loading)return <div className="panel rounded-3xl p-8 text-sm text-white/38">Loading event review queue…</div>;
 return <div className="space-y-5">{message?<div role="status" className="rounded-xl border border-white/[.06] bg-black/10 p-3 text-xs text-white/42">{message}</div>:null}
  <div className="grid gap-3 sm:grid-cols-3">{[["PENDING",pending.length],["APPROVED",reviewed.filter(x=>x.status==="APPROVED").length],["DECLINED",reviewed.filter(x=>x.status==="DECLINED").length]].map(([label,value])=><div key={String(label)} className="panel-soft rounded-2xl p-4"><div className="text-[9px] font-black uppercase tracking-[.13em] text-white/25">{label}</div><div className="mt-2 text-2xl font-semibold text-white/70">{value}</div></div>)}</div>
  {pending.length?<div className="space-y-3">{pending.map(row=><article key={row.id} className="panel rounded-[24px] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><div className="text-[9px] font-black uppercase tracking-[.13em] text-emerald-200/52">{labels[row.event_type]??row.event_type}</div><h3 className="mt-2 text-lg font-semibold text-white/72">{row.title}</h3><div className="mt-2 text-xs text-white/35">{new Date(row.starts_at).toLocaleString()} · {[row.venue_name,row.city,row.state_region,row.country].filter(Boolean).join(" · ")}</div>{row.organizer?<div className="mt-1 text-xs text-white/30">Organizer: {row.organizer}</div>:null}</div><span className="rounded-full border border-amber-200/15 px-2.5 py-1 text-[8px] font-black uppercase tracking-[.1em] text-amber-100/60">Pending</span></div>{row.description?<p className="mt-4 text-sm leading-6 text-white/42">{row.description}</p>:null}{row.note?<div className="mt-4 rounded-xl border border-white/[.06] bg-black/10 p-3 text-xs leading-5 text-white/34"><span className="font-semibold text-white/50">Submitter note:</span> {row.note}</div>:null}<div className="mt-4 flex flex-wrap gap-3 text-[10px]"><Link href={row.source_url} target="_blank" rel="noreferrer" className="font-bold text-emerald-200/60">Verify source ↗</Link>{row.website_url?<Link href={row.website_url} target="_blank" rel="noreferrer" className="font-bold text-white/40">Event website ↗</Link>:null}{row.time_zone?<span className="text-white/24">Timezone: {row.time_zone}</span>:null}</div><div className="mt-5 flex flex-wrap gap-2 border-t border-white/[.055] pt-4"><button type="button" disabled={busy===row.id} onClick={()=>void review(row.id,"APPROVE")} className="rounded-xl border border-emerald-300/18 bg-emerald-300/[.04] px-4 py-2.5 text-xs font-black text-emerald-100/70 disabled:opacity-40">Approve & publish</button><button type="button" disabled={busy===row.id} onClick={()=>void review(row.id,"DECLINE")} className="rounded-xl border border-red-300/15 px-4 py-2.5 text-xs font-black text-red-100/55 disabled:opacity-40">Decline</button></div></article>)}</div>:<div className="panel-soft rounded-2xl p-6 text-sm text-white/35">No pending event suggestions.</div>}
  {reviewed.length?<details className="panel-soft rounded-2xl p-5"><summary className="cursor-pointer text-sm font-semibold text-white/52">Recent reviewed suggestions ({reviewed.length})</summary><div className="mt-4 space-y-2">{reviewed.slice(0,30).map(row=><div key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/[.05] bg-black/10 px-3 py-2.5"><div><div className="text-xs font-semibold text-white/50">{row.title}</div><div className="mt-1 text-[9px] text-white/22">{[row.city,row.state_region].filter(Boolean).join(", ")}</div></div><span className={`text-[8px] font-black uppercase ${row.status==="APPROVED"?"text-emerald-200/55":"text-red-100/45"}`}>{row.status}</span></div>)}</div></details>:null}
 </div>;
}
