"use client";
import { useEffect,useMemo,useState } from "react";

type Animal={id:string;slug:string;common_name:string;scientific_name:string;animal_group:string;description:string|null;tags:string[]|null;published:boolean;reference_data:Record<string,string>|null};
type Plant={id:string;slug:string;name:string;scientific_name:string;plant_group:string;description:string|null;tags:string[]|null;status:string;cultivation_data:Record<string,string>|null};
type Kind="animal"|"plant";
const field="w-full rounded-2xl border border-white/[.08] bg-black/15 px-4 py-3 text-sm text-white outline-none placeholder:text-white/18 focus:border-emerald-300/20";
const area=`${field} min-h-28 resize-y leading-6`;
const animalFields=["taxonomy_notes","natural_history","husbandry","breeding","source_notes"] as const;
const animalLabels:Record<(typeof animalFields)[number],string>={taxonomy_notes:"Taxonomy notes",natural_history:"Natural history",husbandry:"Husbandry",breeding:"Breeding",source_notes:"Sources / review notes"};
const plantFields=["light","temperature","humidity","watering","substrate","feeding","notes","source_notes"] as const;
const plantLabels:Record<(typeof plantFields)[number],string>={light:"Light",temperature:"Temperature",humidity:"Humidity",watering:"Watering",substrate:"Substrate / media",feeding:"Feeding / fertilization",notes:"Cultivation notes",source_notes:"Sources / review notes"};

export function AdminReferenceEditor(){
 const [animals,setAnimals]=useState<Animal[]>([]),[plants,setPlants]=useState<Plant[]>([]),[kind,setKind]=useState<Kind>("animal"),[selectedId,setSelectedId]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const load=()=>fetch("/api/admin/reference",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(d=>{setAnimals(d.animals??[]);setPlants(d.plants??[])}).finally(()=>setLoading(false));
 useEffect(()=>{void load()},[]);
 const rows=kind==="animal"?animals:plants;
 const selected=useMemo(()=>rows.find(r=>r.id===selectedId)??rows[0]??null,[rows,selectedId]);
 function switchKind(next:Kind){setKind(next);setSelectedId("");setMessage("")}
 async function save(form:FormData){if(!selected)return;setSaving(true);setMessage("");const tags=String(form.get("tags")??"").split(",").map(x=>x.trim()).filter(Boolean);let payload:Record<string,unknown>={kind,id:selected.id,description:String(form.get("description")??""),tags};if(kind==="animal"){const reference_data:Record<string,string>=Object.fromEntries(animalFields.map(k=>[k,String(form.get(k)??"")]));payload={...payload,reference_data}}else{const cultivation_data:Record<string,string>=Object.fromEntries(plantFields.map(k=>[k,String(form.get(k)??"")]));payload={...payload,cultivation_data}}const r=await fetch("/api/admin/reference",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(r.ok){setMessage("Saved.");await load()}else setMessage(d.error??"Could not save.");setSaving(false)}
 if(loading)return <div className="panel rounded-3xl p-8 text-sm text-white/30">Loading reference editor…</div>;
 return <div className="grid gap-5 xl:grid-cols-[280px_1fr]">
  <aside className="panel rounded-3xl p-4"><div className="grid grid-cols-2 gap-2"><button onClick={()=>switchKind("animal")} className={`rounded-xl px-3 py-2 text-xs font-bold ${kind==="animal"?"bg-emerald-300 text-[#06100c]":"border border-white/10 text-white/40"}`}>Animals</button><button onClick={()=>switchKind("plant")} className={`rounded-xl px-3 py-2 text-xs font-bold ${kind==="plant"?"bg-emerald-300 text-[#06100c]":"border border-white/10 text-white/40"}`}>Plants</button></div><div className="mt-4 max-h-[560px] space-y-1 overflow-y-auto">{rows.map(r=>{const name=kind==="animal"?(r as Animal).common_name:(r as Plant).name;const scientific=(r as Animal|Plant).scientific_name;return <button key={r.id} onClick={()=>{setSelectedId(r.id);setMessage("")}} className={`w-full rounded-2xl px-3 py-3 text-left ${selected?.id===r.id?"bg-white/[.06]":"hover:bg-white/[.025]"}`}><div className="text-sm font-semibold text-white/65">{name}</div><div className="mt-1 text-[10px] italic text-white/25">{scientific}</div></button>})}</div></aside>
  <section className="panel rounded-3xl p-5 sm:p-6">{selected?<form key={`${kind}-${selected.id}`} action={save} className="space-y-5"><div><div className="section-kicker">{kind==="animal"?(selected as Animal).animal_group:(selected as Plant).plant_group}</div><h3 className="mt-2 text-2xl font-semibold">{kind==="animal"?(selected as Animal).common_name:(selected as Plant).name}</h3><div className="mt-1 text-xs italic text-white/30">{selected.scientific_name}</div></div><label className="block text-xs text-white/40">Overview<textarea name="description" defaultValue={selected.description??""} className={`${area} mt-2`}/></label><label className="block text-xs text-white/40">Tags, comma-separated<input name="tags" defaultValue={(selected.tags??[]).join(", ")} className={`${field} mt-2`}/></label>{kind==="animal"?animalFields.map(k=><label key={k} className="block text-xs text-white/40">{animalLabels[k]}<textarea name={k} defaultValue={(selected as Animal).reference_data?.[k]??""} className={`${area} mt-2`}/></label>):plantFields.map(k=><label key={k} className="block text-xs text-white/40">{plantLabels[k]}<textarea name={k} defaultValue={(selected as Plant).cultivation_data?.[k]??""} className={`${area} mt-2`}/></label>)}<div className="flex flex-wrap items-center gap-3"><button disabled={saving} className="rounded-xl bg-emerald-300 px-5 py-3 text-xs font-black text-[#06100c] disabled:opacity-50">{saving?"Saving…":"Save reference"}</button>{message&&<span className="text-xs text-white/40">{message}</span>}<span className="ml-auto text-[10px] uppercase tracking-[.12em] text-white/20">Private admin editor</span></div></form>:<div className="py-16 text-center text-sm text-white/30">No records available.</div>}</section>
 </div>;
}
