"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { GreenTreePythonArt } from "@/components/ArborealArt";

type AnimalRecord={slug:string;common_name:string;scientific_name:string;animal_group:string;tags:string[];published:boolean};
export function AnimalDatabaseExplorer(){
 const [records,setRecords]=useState<AnimalRecord[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[group,setGroup]=useState("All"),[publishedOnly,setPublishedOnly]=useState(false);
 useEffect(()=>{let live=true;fetch("/api/catalog/animals").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>{if(live)setRecords(d.rows??[])}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[]);
 const groups=useMemo(()=>["All",...Array.from(new Set(records.map(r=>r.animal_group)))],[records]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return records.filter(r=>(group==="All"||r.animal_group===group)&&(!publishedOnly||r.published)&&(!q||[r.common_name,r.scientific_name,r.animal_group,...(r.tags??[])].join(" ").toLowerCase().includes(q)))},[records,query,group,publishedOnly]);
 return <><section className="mx-auto max-w-7xl px-5 pb-8 sm:px-6"><div className="panel rounded-3xl p-4 sm:p-5"><div className="grid gap-3 lg:grid-cols-[1fr_auto_auto] lg:items-center"><label className="relative block"><span className="sr-only">Search animal database</span><span className="absolute left-4 top-1/2 -translate-y-1/2 text-white/25">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search species, scientific name, locality topic…" className="w-full rounded-2xl border border-white/[.08] bg-black/15 py-3 pl-10 pr-4 text-sm outline-none placeholder:text-white/20"/></label><div className="hide-scrollbar flex gap-1 overflow-x-auto rounded-2xl border border-white/[.06] p-1">{groups.map(g=><button key={g} onClick={()=>setGroup(g)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-[10px] font-bold uppercase ${group===g?"bg-emerald-300 text-[#06100c]":"text-white/34"}`}>{g}</button>)}</div><button onClick={()=>setPublishedOnly(v=>!v)} className={`rounded-2xl border px-4 py-3 text-[10px] font-bold uppercase ${publishedOnly?"border-emerald-300/20 text-emerald-200":"border-white/[.07] text-white/34"}`}>Published only</button></div><div className="mt-3 flex justify-between text-[10px] uppercase tracking-[.12em] text-white/22"><span>{loading?"Loading Supabase…":`${visible.length} records shown`}</span><span>Live catalog</span></div></div></section><section className="mx-auto max-w-7xl px-5 pb-12 sm:px-6">{!loading&&visible.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map(r=>{const featured=r.slug==="green-tree-python";const body=<><div className={`relative h-48 overflow-hidden border-b border-white/[.06] ${featured?"bg-[#08130e]":"grid-surface"}`}>{featured?<div className="absolute inset-x-0 bottom-0 h-[95%]"><GreenTreePythonArt/></div>:<div className="absolute inset-0 grid place-items-center text-3xl text-white/10">◇</div>}<span className="absolute left-4 top-4 rounded-full border border-white/[.08] bg-black/30 px-3 py-1.5 text-[9px] font-black uppercase text-white/50">{r.published?"Published":"Planned"}</span></div><div className="p-5"><div className="text-[9px] font-bold uppercase text-white/24">{r.animal_group}</div><h2 className="mt-2 text-xl font-semibold">{r.common_name}</h2><div className="mt-1 text-xs italic text-white/32">{r.scientific_name}</div><div className="mt-4 flex flex-wrap gap-1.5">{(r.tags??[]).map(t=><span key={t} className="rounded-full border border-white/[.06] px-2.5 py-1 text-[10px] text-white/30">{t}</span>)}</div></div></>;return r.published?<Link key={r.slug} href={`/animals/${r.slug}`} className="panel overflow-hidden rounded-3xl">{body}</Link>:<article key={r.slug} className="panel overflow-hidden rounded-3xl opacity-75">{body}</article>})}</div>:!loading?<div className="panel rounded-3xl py-16 text-center text-white/40">No matching records.</div>:null}</section></>;
}
