"use client";
import { useState } from "react";

type Props={postId:string;body:string;tags:string[];videoUrl:string|null};

export function CommunityPostOwnerMenu({postId,body,tags,videoUrl}:Props){
  const [busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[text,setText]=useState(body),[tagText,setTagText]=useState(tags.join(", ")),[video,setVideo]=useState(videoUrl??""),[error,setError]=useState("");
  async function save(){if(busy)return;setBusy(true);setError("");const cleanTags=tagText.split(",").map(x=>x.trim()).filter(Boolean).slice(0,4);const r=await fetch(`/api/community/posts/${postId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:text,tags:cleanTags,video_url:video})});const d=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setError(d.error??"Could not update post.");return}setEditing(false);window.dispatchEvent(new Event("community-posted"));}
  async function remove(){if(busy||!confirm("Remove this post from the community feed?"))return;setBusy(true);const r=await fetch(`/api/community/posts/${postId}`,{method:"DELETE"});setBusy(false);if(r.ok)window.dispatchEvent(new Event("community-posted"));else setError("Could not remove that post.");}
  if(editing)return <div className="ml-auto w-full max-w-md rounded-2xl border border-white/[.07] bg-black/20 p-3"><textarea value={text} onChange={e=>setText(e.target.value.slice(0,1200))} rows={4} className="w-full resize-none rounded-xl border border-white/[.07] bg-black/20 p-3 text-xs outline-none" placeholder="Edit your post…"/><input value={tagText} onChange={e=>setTagText(e.target.value)} className="mt-2 w-full rounded-xl border border-white/[.07] bg-black/20 px-3 py-2 text-xs outline-none" placeholder="Tags, separated by commas"/><input value={video} onChange={e=>setVideo(e.target.value)} className="mt-2 w-full rounded-xl border border-white/[.07] bg-black/20 px-3 py-2 text-xs outline-none" placeholder="Optional HTTPS video link"/>{error&&<div className="mt-2 text-[10px] text-red-200/65">{error}</div>}<div className="mt-3 flex gap-2"><button disabled={busy} onClick={save} className="rounded-lg bg-emerald-300 px-3 py-2 text-[10px] font-black text-[#06100c] disabled:opacity-40">{busy?"Saving…":"Save changes"}</button><button disabled={busy} onClick={()=>{setEditing(false);setText(body);setTagText(tags.join(", "));setVideo(videoUrl??"");setError("")}} className="rounded-lg border border-white/10 px-3 py-2 text-[10px] font-bold text-white/40 disabled:opacity-40">Cancel</button></div></div>;
  return <div className="ml-auto flex gap-2"><button disabled={busy} onClick={()=>setEditing(true)} className="rounded-lg border border-emerald-300/10 px-3 py-2 text-[10px] font-bold text-emerald-200/55 hover:bg-emerald-300/[.04] disabled:opacity-40">Edit post</button><button disabled={busy} onClick={remove} className="rounded-lg border border-red-300/10 px-3 py-2 text-[10px] font-bold text-red-200/55 hover:bg-red-300/[.04] disabled:opacity-40">{busy?"Removing…":"Remove post"}</button></div>;
}
