"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { AnimalCatalogFields } from "@/components/AnimalCatalogFields";

type Listing={id:string;category:string;title:string;description:string|null;price:number;species_id:string|null;locality_id:string|null;public_origin:string|null;morph:string|null;sex:string|null;age_or_year:string|null;lineage:string|null;seller_location:string|null;status:string;image_urls:string[]|null};
export function EditListingForm({listing}:{listing:Listing}){
 const router=useRouter(); const [busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);const body=Object.fromEntries(fd.entries());const r=await fetch(`/api/marketplace/listings/${listing.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||"Could not update listing");setBusy(false);return}router.push(`/marketplace/${listing.id}`);router.refresh()}
 const field="mt-2 w-full rounded-xl border border-white/10 bg-[#08130e] p-3 text-white";
 return <form onSubmit={submit} className="panel rounded-3xl p-5 sm:p-7"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs text-white/45">Price · USD<input name="price" defaultValue={listing.price} required type="number" min="0" step="0.01" className={field}/></label><label className="text-xs text-white/45">Status<select name="status" defaultValue={listing.status} className={field}><option value="ACTIVE">Active</option><option value="SOLD">Sold</option><option value="DRAFT">Draft</option><option value="REMOVED">Removed</option></select></label><label className="sm:col-span-2 text-xs text-white/45">Listing title<input name="title" defaultValue={listing.title} required maxLength={140} className={field}/></label><label className="sm:col-span-2 text-xs text-white/45">Description<textarea name="description" defaultValue={listing.description??""} rows={5} className={field}/></label>{listing.category==="ANIMAL"&&<><AnimalCatalogFields speciesId={listing.species_id??""} localityId={listing.locality_id??""}/><label className="text-xs text-white/45">Origin<select name="public_origin" defaultValue={listing.public_origin??"CAPTIVE_BRED"} className={field}><option value="CAPTIVE_BRED">Captive Bred</option><option value="IMPORT">Import</option></select></label><label className="text-xs text-white/45">Sex<select name="sex" defaultValue={listing.sex??""} className={field}><option value="">Unspecified</option><option value="Male">Male</option><option value="Female">Female</option></select></label><label className="text-xs text-white/45">Morph / trait<input name="morph" defaultValue={listing.morph??""} className={field}/></label><label className="text-xs text-white/45">Age / birth year<input name="age_or_year" defaultValue={listing.age_or_year??""} className={field}/></label><label className="sm:col-span-2 text-xs text-white/45">Lineage / parents<input name="lineage" defaultValue={listing.lineage??""} className={field}/></label></>}<label className="sm:col-span-2 text-xs text-white/45">Seller location<input name="seller_location" defaultValue={listing.seller_location??""} className={field}/></label></div><p className="mt-4 text-xs text-white/35">{listing.image_urls?.length??0} existing photo{listing.image_urls?.length===1?"":"s"} attached.</p>{error&&<div className="mt-4 text-sm text-red-300">{error}</div>}<div className="mt-6 flex gap-3"><button disabled={busy} className="rounded-xl bg-emerald-300 px-5 py-3 text-sm font-black text-[#06100c] disabled:opacity-50">{busy?"Saving…":"Save changes"}</button><button type="button" onClick={()=>router.push(`/marketplace/${listing.id}`)} className="rounded-xl border border-white/10 px-5 py-3 text-sm font-bold text-white/70">Cancel</button></div></form>
}
