"use client";

import Link from "next/link";
import { useEffect,useState } from "react";

type Row={id:string;title:string;event_type:string;starts_at:string;city:string;state_region:string|null;country:string;source_url:string;status:"PENDING"|"APPROVED"|"DECLINED";created_at:string;reviewed_at:string|null};
const labels:Record<string,string>={REPTILE_EXPO:"Reptile expo",BREEDER_EVENT:"Breeder event",EDUCATION:"Education",PLANT_EVENT:"Plant event",COMMUNITY_MEETUP:"Community meetup",OTHER:"Other"};

export function EventSubmissionStatus(){
 const [signedIn,setSignedIn]=useState<boolean|null>(null),[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 async function load(){try{const response=await fetch("/api/events/submissions",{cache:"no-store"});const data=await response.json().catch(()=>null) as {signedIn?:boolean;rows?:Row[]}|null;if(response.ok&&data){setSignedIn(Boolean(data.signedIn));setRows(data.rows??[])}}finally{setLoading(false)}}
 useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener("event-submitted",refresh);return()=>window.removeEventListener("event-submitted",refresh)},[]);
 async function withdraw(id:string){if(!window.confirm("Withdraw this pending event suggestion?"))return;setMessage("Withdrawing…");const response=await fetch(`/api/events/submissions?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(response.ok){setRows(current=>current.filter(row=>row.id!==id));setMessage("Suggestion withdrawn.")}else setMessage("Could not withdraw that suggestion.")}
 if(loading)return <div className="panel-soft rounded-2xl p-5 text-xs text-white/32">Checking your event suggestions…</div>;
 if(signedIn===false)return <div className="panel-soft rounded-2xl p-5"><div className="font-semibold text-white/58">Track your suggestions</div><p className="mt-2 text-xs leading-5 text-white/32">Sign in before submitting an event to see review status here.</p><Link href="/login?next=%2Fevents%3Fsuggest%3D1" className="mt-4 inline-block text-xs font-bold text-emerald-200/65">Sign in →</Link></div>;
 return <div className="panel rounded-[26px] p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="section-kicker">Your suggestions</div><h2 className="mt-2 text-xl font-semibold">Event review status</h2></div><span className="text-[10px] font-black uppercase tracking-[.12em] text-white/24">{rows.length} submitted</span></div>{message?<div role="status" className="mt-3 text-xs text-white/38">{message}</div>:null}{rows.length?<div className="mt-5 space-y-3">{rows.map(row=><div key={row.id} className="rounded-2xl border border-white/[.06] bg-black/10 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-semibold text-white/68">{row.title}</div><div className="mt-1 text-xs text-white/32">{labels[row.event_type]??row.event_type} · {new Date(row.starts_at).toLocaleDateString()} · {[row.city,row.state_region,row.country].filter(Boolean).join(", ")}</div></div><span className={`rounded-full border px-2.5 py-1 text-[8px] font-black uppercase tracking-[.1em] ${row.status==="APPROVED"?"border-emerald-300/15 text-emerald-100/65":row.status==="DECLINED"?"border-red-300/15 text-red-100/55":"border-amber-200/15 text-amber-100/60"}`}>{row.status}</span></div><div className="mt-3 flex flex-wrap items-center gap-3"><Link href={row.source_url} target="_blank" rel="noreferrer" className="text-[10px] font-bold text-emerald-200/50">Source ↗</Link>{row.status==="PENDING"?<button type="button" onClick={()=>void withdraw(row.id)} className="text-[10px] font-bold text-red-100/45 hover:text-red-100/70">Withdraw</button>:null}</div></div>)}</div>:<p className="mt-4 text-xs leading-5 text-white/30">You have not submitted an event suggestion yet.</p>}</div>
}
