import Link from "next/link";
import { notFound } from "next/navigation";
import { SUPABASE_AUTH_KEY,SUPABASE_AUTH_URL } from "@/lib/supabase-auth";

export const dynamic="force-dynamic";
type ReferenceData={taxonomy_notes?:string;natural_history?:string;husbandry?:string;breeding?:string;source_notes?:string};
type Species={id:string;slug:string;common_name:string;scientific_name:string;animal_group:string;description:string|null;tags:string[]|null;published:boolean;market_group_note:string|null;reference_data:ReferenceData|null};
type Locality={id:string;name:string;display_order:number|null;review_flag:boolean;notes:string|null};
type Listing={id:string;title:string;price:number|null;currency:string;public_origin:string|null;morph:string|null;image_urls:string[]|null};
const h={apikey:SUPABASE_AUTH_KEY,Authorization:`Bearer ${SUPABASE_AUTH_KEY}`};
const has=(v?:string)=>Boolean(v?.trim());

export default async function AnimalRecordPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;const clean=decodeURIComponent(slug).trim();if(!clean)notFound();
  const r=await fetch(`${SUPABASE_AUTH_URL}/rest/v1/species?slug=eq.${encodeURIComponent(clean)}&published=eq.true&select=id,slug,common_name,scientific_name,animal_group,description,tags,published,market_group_note,reference_data&limit=1`,{headers:h,cache:"no-store"});
  if(!r.ok)notFound();const rows:Species[]=await r.json();const species=rows[0];if(!species)notFound();
  const [l,m]=await Promise.all([
    fetch(`${SUPABASE_AUTH_URL}/rest/v1/localities?species_id=eq.${species.id}&active=eq.true&select=id,name,display_order,review_flag,notes&order=display_order.asc`,{headers:h,cache:"no-store"}),
    fetch(`${SUPABASE_AUTH_URL}/rest/v1/marketplace_listings?species_id=eq.${species.id}&status=eq.ACTIVE&select=id,title,price,currency,public_origin,morph,image_urls&order=created_at.desc&limit=6`,{headers:h,cache:"no-store"})
  ]);
  const localities:Locality[]=l.ok?await l.json():[];const listings:Listing[]=m.ok?await m.json():[];const ref=species.reference_data??{};
  const coverage=[
    ["Identity",true,"Common name, scientific name and animal group"],
    ["Locality",localities.length>0,localities.length?`${localities.length} active locality record${localities.length===1?"":"s"}`:"No locality records published"],
    ["Husbandry",has(ref.husbandry),has(ref.husbandry)?"Reviewed husbandry notes available":"Structured husbandry fields not published yet"],
    ["Breeding",has(ref.breeding),has(ref.breeding)?"Reviewed breeding notes available":"Structured breeding fields not published yet"]
  ] as const;
  const referenceSections=[["Taxonomy notes",ref.taxonomy_notes],["Natural history",ref.natural_history],["Husbandry",ref.husbandry],["Breeding",ref.breeding]] as const;
  return <main className="mx-auto max-w-6xl px-5 py-10 sm:px-6">
    <Link href="/animals" className="text-xs font-bold text-emerald-200/70">← Animal Database</Link>
    <section className="panel mt-5 rounded-[32px] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="section-kicker">{species.animal_group}</div><h1 className="mt-3 text-4xl font-semibold tracking-[-.035em] sm:text-5xl">{species.common_name}</h1><div className="mt-2 text-base italic text-white/38">{species.scientific_name}</div></div><span className="rounded-full border border-emerald-300/15 bg-emerald-300/[.05] px-3 py-1.5 text-[10px] font-black uppercase tracking-[.12em] text-emerald-200/70">Published reference</span></div>{species.description&&<p className="mt-7 max-w-3xl text-sm leading-7 text-white/55">{species.description}</p>}{species.tags?.length?<div className="mt-6 flex flex-wrap gap-2">{species.tags.map(t=><span key={t} className="rounded-full border border-white/[.07] px-3 py-1.5 text-[10px] text-white/35">{t}</span>)}</div>:null}</section>

    <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{coverage.map(([label,ready,text])=><div key={label} className="panel-soft rounded-2xl p-4"><div className="flex items-center justify-between"><div className="text-[9px] font-black uppercase tracking-[.14em] text-white/25">{label}</div><span className={`rounded-full px-2 py-1 text-[8px] font-black uppercase ${ready?"bg-emerald-300/[.08] text-emerald-200/70":"bg-white/[.035] text-white/25"}`}>{ready?"Available":"Pending"}</span></div><p className="mt-3 text-xs leading-5 text-white/35">{text}</p></div>)}</section>

    <section className="mt-6 grid gap-5 lg:grid-cols-[1fr_.9fr]"><div className="panel rounded-3xl p-6"><div className="section-kicker">Locality structure</div><h2 className="mt-3 text-2xl font-semibold">Cataloged locality records</h2>{species.market_group_note&&<p className="mt-3 text-xs leading-5 text-amber-100/45">{species.market_group_note}</p>}{localities.length?<div className="mt-5 grid gap-2 sm:grid-cols-2">{localities.map(x=><div key={x.id} className="rounded-2xl border border-white/[.06] bg-white/[.02] px-4 py-3"><div className="flex items-center justify-between gap-3"><span className="text-sm text-white/60">{x.name}</span>{x.review_flag&&<span className="rounded-full border border-amber-300/15 px-2 py-1 text-[8px] font-bold uppercase text-amber-200/60">Review</span>}</div>{x.notes&&<p className="mt-2 text-[11px] leading-5 text-white/28">{x.notes}</p>}</div>)}</div>:<p className="mt-4 text-sm text-white/32">No locality records are published for this species yet.</p>}</div><div className="space-y-4"><div className="panel rounded-3xl p-6"><div className="section-kicker">Reference boundaries</div><h2 className="mt-2 text-lg font-semibold">Only reviewed stored fields are shown as facts.</h2><p className="mt-3 text-xs leading-5 text-white/34">Reference sections stay visibly pending until content is entered through the private publishing workflow.</p></div><Link href="/community" className="panel block rounded-3xl p-6 transition hover:bg-white/[.025]"><div className="section-kicker">Community</div><div className="mt-2 font-semibold">Keeper discussion →</div><p className="mt-2 text-xs leading-5 text-white/32">Questions and keeper experience stay connected without becoming reference facts automatically.</p></Link></div></section>

    <section className="mt-8"><div className="mb-4"><div className="section-kicker">Reference content</div><h2 className="mt-2 text-2xl font-semibold">Reviewed species notes</h2></div><div className="grid gap-4 md:grid-cols-2">{referenceSections.map(([label,value])=><article key={label} className="panel rounded-3xl p-6"><div className="flex items-center justify-between gap-3"><div className="text-sm font-semibold text-white/65">{label}</div><span className={`rounded-full px-2 py-1 text-[8px] font-black uppercase ${has(value)?"bg-emerald-300/[.08] text-emerald-200/70":"bg-white/[.035] text-white/25"}`}>{has(value)?"Available":"Pending"}</span></div>{has(value)?<p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-white/48">{value}</p>:<p className="mt-4 text-xs leading-5 text-white/28">No reviewed {label.toLowerCase()} have been published yet.</p>}</article>)}</div>{has(ref.source_notes)&&<div className="panel-soft mt-4 rounded-2xl p-4 text-xs leading-6 text-white/32"><span className="font-semibold text-white/50">Sources / review notes:</span> {ref.source_notes}</div>}</section>

    <section className="mt-8"><div className="mb-4 flex items-end justify-between gap-4"><div><div className="section-kicker">Marketplace</div><h2 className="mt-2 text-2xl font-semibold">Active {species.common_name} listings</h2></div><Link href={`/marketplace?species=${species.id}`} className="text-xs font-bold text-emerald-200/70">View all →</Link></div>{listings.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{listings.map(x=><Link key={x.id} href={`/marketplace/${x.id}`} className="panel overflow-hidden rounded-3xl"><div className="grid-surface grid h-40 place-items-center overflow-hidden border-b border-white/[.06]">{x.image_urls?.[0]?<img src={x.image_urls[0]} alt={x.title} className="h-full w-full object-cover"/>:<span className="text-white/15">◇</span>}</div><div className="p-5"><div className="text-[9px] font-black uppercase tracking-[.12em] text-emerald-300/50">{x.public_origin==="CAPTIVE_BRED"?"Captive Bred":x.public_origin==="IMPORT"?"Import":"Animal"}</div><h3 className="mt-2 font-semibold">{x.title}</h3>{x.morph&&<div className="mt-1 text-xs text-white/32">{x.morph}</div>}<div className="mt-3 text-lg font-semibold">{x.price==null?"Contact seller":`$${Number(x.price).toLocaleString()}`}</div></div></Link>)}</div>:<div className="panel rounded-3xl py-10 text-center text-sm text-white/32">No active listings for this species right now.</div>}</section>
  </main>;
}
