import Link from "next/link";
import { notFound } from "next/navigation";
import { SUPABASE_AUTH_KEY,SUPABASE_AUTH_URL } from "@/lib/supabase-auth";

export const dynamic="force-dynamic";
type Species={id:string;slug:string;common_name:string;scientific_name:string;animal_group:string;description:string|null;tags:string[]|null;published:boolean};
type Locality={id:string;name:string;display_order:number|null};

export default async function AnimalRecordPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;const clean=decodeURIComponent(slug).trim();if(!clean)notFound();
  const headers={apikey:SUPABASE_AUTH_KEY,Authorization:`Bearer ${SUPABASE_AUTH_KEY}`};
  const r=await fetch(`${SUPABASE_AUTH_URL}/rest/v1/species?slug=eq.${encodeURIComponent(clean)}&published=eq.true&select=id,slug,common_name,scientific_name,animal_group,description,tags,published&limit=1`,{headers,cache:"no-store"});
  if(!r.ok)notFound();const rows:Species[]=await r.json();const species=rows[0];if(!species)notFound();
  const l=await fetch(`${SUPABASE_AUTH_URL}/rest/v1/localities?species_id=eq.${species.id}&active=eq.true&select=id,name,display_order&order=display_order.asc`,{headers,cache:"no-store"});
  const localities:Locality[]=l.ok?await l.json():[];
  return <main className="mx-auto max-w-6xl px-5 py-10 sm:px-6"><Link href="/animals" className="text-xs font-bold text-emerald-200/70">← Animal Database</Link><section className="panel mt-5 rounded-[32px] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="section-kicker">{species.animal_group}</div><h1 className="mt-3 text-4xl font-semibold tracking-[-.035em] sm:text-5xl">{species.common_name}</h1><div className="mt-2 text-base italic text-white/38">{species.scientific_name}</div></div><span className="rounded-full border border-emerald-300/15 bg-emerald-300/[.05] px-3 py-1.5 text-[10px] font-black uppercase tracking-[.12em] text-emerald-200/70">Published reference</span></div>{species.description&&<p className="mt-7 max-w-3xl text-sm leading-7 text-white/55">{species.description}</p>}{species.tags?.length?<div className="mt-6 flex flex-wrap gap-2">{species.tags.map(t=><span key={t} className="rounded-full border border-white/[.07] px-3 py-1.5 text-[10px] text-white/35">{t}</span>)}</div>:null}</section><section className="mt-6 grid gap-5 lg:grid-cols-[1fr_.9fr]"><div className="panel rounded-3xl p-6"><div className="section-kicker">Localities</div><h2 className="mt-3 text-2xl font-semibold">Cataloged locality records</h2>{localities.length?<div className="mt-5 grid gap-2 sm:grid-cols-2">{localities.map(x=><div key={x.id} className="rounded-2xl border border-white/[.06] bg-white/[.02] px-4 py-3 text-sm text-white/55">{x.name}</div>)}</div>:<p className="mt-4 text-sm text-white/32">No locality records are published for this species yet.</p>}</div><div className="space-y-4"><Link href={`/marketplace?species=${species.id}`} className="panel block rounded-3xl p-6 transition hover:bg-emerald-300/[.025]"><div className="section-kicker">Marketplace</div><div className="mt-2 font-semibold">See active listings →</div><p className="mt-2 text-xs leading-5 text-white/32">Browse live inventory without mixing seller listings into reference facts.</p></Link><Link href="/community" className="panel block rounded-3xl p-6 transition hover:bg-white/[.025]"><div className="section-kicker">Community</div><div className="mt-2 font-semibold">Keeper discussion →</div><p className="mt-2 text-xs leading-5 text-white/32">Questions and keeper experience remain connected but distinct from the database record.</p></Link></div></section></main>;
}
